plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    // تحديد الحزمة الأساسية للتطبيق
    namespace 'com.call.w'
    compileSdk 34

    defaultConfig {
        // معرف التطبيق (يجب أن يتطابق مع الحزمة المطلوبة)
        applicationId "com.call.w"
        
        // إصدار 24 مناسب لعمل التطبيق بشكل ممتاز ودعم الواجهات
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    // مكاتب أندرويد الأساسية ودعم Kotlin
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
